### ISSUE TITLE
can't delete chats

### ISSUE THREAD

**Issue by somrat420** [chat21/chat21-android-demo#14] opened 2018-05-27 09:43 UTC
Expected behavior
it should be delete chat when click on delete

Actual behavior
when click on delete it can't able to delete chats

How to reproduce
download the app and run it
scroll on Home button and select a contact
then come to Chat sector
and try to delete a chat
Browser/App version: chat21 1.0.9
Operating system: android 6.0

**Comment by stefanodp91** [comment] 2018-05-30 08:13
possible duplicate of #13

**Closed by stefanodp91** 2018-05-30 08:13 UTC
Labels: duplicate
